version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: netflix_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: netflix
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: netflix_redis
    ports:
      - "6379:6379"